FROM nvcr.io/nvidia/pytorch:20.11-py3
#RUN conda install pytorch=1.4.0 torchvision torchaudio cudatoolkit=10.1 -c pytorch

RUN pip install   pytorch-lightning albumentations
RUN pip install opencv-python-headless
RUN pip install focal_loss_torch

#RUN pip uninstall -y tb-nightly tensorboardX tensorboard
